[summary]
# This will be shown in the title page as "project_name Audit Report"
# As auditors can be formatted further, their names are in lead_auditors.md
project_name = Bulla Factoring \& Core Contracts V2
report_version = 2.0

# team_name engaged with LPHAC to review project_name
team_name = Bulla Network
team_website = https://www.bulla.network/
private_github = https://github.com/LPHAC/bulla-review-2.git
project_github_1 = https://github.com/bulla-network/factoring-contracts.git
initial_commit_hash_1 = 063ed28aae97f6f5ffbc3c75a9b981ac89995c1e
final_commit_hash_1 = b003dca99a9094a231988f27f1ed74cff78e8de7
project_github_2 = https://github.com/bulla-network/bulla-contracts-V2.git
initial_commit_hash_2 = 256561d6a7a214975de9146503e54cf89362736c
final_commit_hash_2 = 070653fe0e54b8481bb5e45c8ba04884fa5496e4

# Information for Summary table
review_timeline = Aug 11th - Aug 19th
review_methods = Manual Review

